-- Generated by pushpay-gen
-- Input file: PushPay_Onboarding_Template.xlsx
-- Template client id: per-client, from the 'template_client_id' column
-- Generated at: 2026-07-12T14:09:34
--
-- Run top-to-bottom in auto-commit; a failed statement affects only that client.
-- Capture full console output (NOTICEs + errors) and paste on the change ticket.

-- Client C1 : Acme Trading LLC (template client 1003, 3 beneficiaries)
SELECT onboard_pushpay_client_with_benes(
    p_template_client_id => 1003,
    p_client => '{"name1":"Acme Trading LLC","country":"USA","contact_email":"acme@example.com","transaction_manager":"TM-NORTH"}'::jsonb,
    p_benes  => '[
      {"bene_name":"Supplier One","account_number":"004501234567","bene_bank_name":"HDFC Bank","swift_code":"HDFCINBB","bene_addr_country":"India","bene_addr_city":"Pune"},
      {"bene_name":"Supplier One","account_number":"004501234567","bene_bank_name":"HDFC Bank","swift_code":"HDFCINBB","bene_addr_country":"India","bene_addr_city":"Pune"},
      {"bene_name":"Supplier One","account_number":"004501234567","bene_bank_name":"HDFC Bank","swift_code":"HDFCINBB","bene_addr_country":"India","bene_addr_city":"Pune"}
    ]'::jsonb);

-- Client C2 : Acme Trading LLC1 (template client 1001, 7 beneficiaries)
SELECT onboard_pushpay_client_with_benes(
    p_template_client_id => 1001,
    p_client => '{"name1":"Acme Trading LLC1","country":"India","contact_email":"acme@example.com","transaction_manager":"TM-NORTH"}'::jsonb,
    p_benes  => '[
      {"bene_name":"Supplier One","account_number":"004501234567","bene_bank_name":"HDFC Bank","swift_code":"HDFCINBB","bene_addr_country":"India","bene_addr_city":"Pune"},
      {"bene_name":"Supplier One","account_number":"004501234567","bene_bank_name":"HDFC Bank","swift_code":"HDFCINBB","bene_addr_country":"India","bene_addr_city":"Pune"},
      {"bene_name":"Supplier One","account_number":"004501234567","bene_bank_name":"HDFC Bank","swift_code":"HDFCINBB","bene_addr_country":"India","bene_addr_city":"Pune"},
      {"bene_name":"Supplier One","account_number":"004501234567","bene_bank_name":"HDFC Bank","swift_code":"HDFCINBB","bene_addr_country":"India","bene_addr_city":"Pune"},
      {"bene_name":"Supplier One","account_number":"004501234567","bene_bank_name":"HDFC Bank","swift_code":"HDFCINBB","bene_addr_country":"India","bene_addr_city":"Pune"},
      {"bene_name":"Supplier One","account_number":"004501234567","bene_bank_name":"HDFC Bank","swift_code":"HDFCINBB","bene_addr_country":"India","bene_addr_city":"Pune"},
      {"bene_name":"Supplier One","account_number":"004501234567","bene_bank_name":"HDFC Bank","swift_code":"HDFCINBB","bene_addr_country":"India","bene_addr_city":"Pune"}
    ]'::jsonb);

-- Client C3 : Acme Trading LLC2 (template client 1001, 1 beneficiaries)
SELECT onboard_pushpay_client_with_benes(
    p_template_client_id => 1001,
    p_client => '{"name1":"Acme Trading LLC2","country":"India","contact_email":"acme@example.com","transaction_manager":"TM-NORTH"}'::jsonb,
    p_benes  => '[
      {"bene_name":"Supplier One","account_number":"004501234567","bene_bank_name":"HDFC Bank","swift_code":"HDFCINBB","bene_addr_country":"India","bene_addr_city":"Pune"}
    ]'::jsonb);

